### ISSUE TITLE
Social media button border doesn't use $darkgrey

### ISSUE THREAD

**Issue by akd-io** [akd-io/akd-io-website#7]
The social media buttons are currently using `black` instead of `$darkgrey`. Border should match the button's background.

```scss
.card {
  [...]
  .social-media {
    [...]
    a {
      [...]
      border: 1px solid black;
      border-radius: 0.3em;
      background: $darkgrey;
      [...]
    }
  }
}
```
